--- #YAML:1.0
name:               Tie-FileHandle-Split
version:            0.9
abstract:           Filehandle tie that captures, splits and stores output into files in a given path.
author:
    - Gonzalo Barco <gbarco@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Tie::FileHandle::Base:  0.1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
